global using System;
global using System.Collections.Generic;
global using System.Collections.ObjectModel;
global using System.ComponentModel;
global using System.IO;
global using System.Linq;
global using System.Windows.Input;
global using System.Windows.Media;
global using DesktopCore;
